from pathlib import Path

path = Path('packages/alg/src/detectors/threeFactor/features/g3.teeRecovery.ts')
text = path.read_text()

# V6 duplicate no-op refit elimination.
old = '''\t\t\tlet compatible = compatibleWith(fit);\n\t\t\t// The first pose may be underdetermined by a tiny shard. Refit the union,\n\t\t\t// then retain only complete components that still fit the shared pose.\n\t\t\tfor (let pass = 0; pass < 2; pass++) {\n\t\t\t\tconst union = compatible.flatMap((entry) => entry.pixels);\n\t\t\t\tif (union.length === 0) break;\n\t\t\t\tfit = fitComponent(union, seed.component, target, viewportTopPx, halfWidth, halfHeight, thickness);\n\t\t\t\tconst next = compatibleWith(fit);\n\t\t\t\tif (next.map((entry) => entry.component.label).join(',') === compatible.map((entry) => entry.component.label).join(',')) break;\n\t\t\t\tcompatible = next;\n\t\t\t}\n'''
new = '''\t\t\tlet compatible = compatibleWith(fit);\n\t\t\t// Refit only when the first pose actually attracted another component.\n\t\t\t// If compatible is just the seed, union is byte-for-byte the exact pixels\n\t\t\t// fit above, so solving the same exhaustive optimization again is a no-op.\n\t\t\tif (compatible.length > 1) {\n\t\t\t\tfor (let pass = 0; pass < 2; pass++) {\n\t\t\t\t\tconst union = compatible.flatMap((entry) => entry.pixels);\n\t\t\t\t\tif (union.length === 0) break;\n\t\t\t\t\tfit = fitComponent(union, seed.component, target, viewportTopPx, halfWidth, halfHeight, thickness);\n\t\t\t\t\tconst next = compatibleWith(fit);\n\t\t\t\t\tif (next.map((entry) => entry.component.label).join(',') === compatible.map((entry) => entry.component.label).join(',')) break;\n\t\t\t\t\tcompatible = next;\n\t\t\t\t}\n\t\t\t}\n'''
if text.count(old) != 1:
    raise SystemExit(f'dedup block count={text.count(old)}')
text = text.replace(old, new, 1)

old_loop = '''\tfor (let y = minCenterY; y <= maxCenterY + 1e-9; y += 0.5) {\n\t\tfor (let x = minCenterX; x <= maxCenterX + 1e-9; x += 0.5) {\n\t\t\tconst rayX = badgeX - x;\n\t\t\tconst rayY = badgeY - y;\n\t\t\tconst rayLength = Math.hypot(rayX, rayY);\n\t\t\tconst rayC = rayLength === 0 ? 1 : rayX / rayLength;\n\t\t\tconst rayS = rayLength === 0 ? 0 : rayY / rayLength;\n\t\t\tfor (const axisOffset of axisOffsets) consider(x, y, rayC, rayS, axisOffset);\n\t\t}\n\t}\n'''
new_loop = '''\t// Exact broad phase over the SAME center lattice. Every pixel of any legal\n\t// rotated tee must satisfy both necessary bounds below. They only prove a\n\t// center impossible; they never remove a component, badge, or legal pose.\n\tconst outerRadiusSq = outerRadius * outerRadius;\n\tlet rayFrameHalfWidth = 0;\n\tlet rayFrameHalfHeight = 0;\n\tfor (const axisOffset of axisOffsets) {\n\t\t// Projection of the legal outer rectangle onto the un-offset badge-ray\n\t\t// axes. Max over the exact discrete angle lattice used by consider().\n\t\trayFrameHalfWidth = Math.max(\n\t\t\trayFrameHalfWidth,\n\t\t\touterHalfWidth * Math.abs(axisOffset.c) + outerHalfHeight * Math.abs(axisOffset.s)\n\t\t);\n\t\trayFrameHalfHeight = Math.max(\n\t\t\trayFrameHalfHeight,\n\t\t\touterHalfWidth * Math.abs(axisOffset.s) + outerHalfHeight * Math.abs(axisOffset.c)\n\t\t);\n\t}\n\tconst broadPhaseEpsilon = 1e-9;\n\tfor (let y = minCenterY; y <= maxCenterY + 1e-9; y += 0.5) {\n\t\tfor (let x = minCenterX; x <= maxCenterX + 1e-9; x += 0.5) {\n\t\t\tlet possible = true;\n\t\t\tfor (const point of pixels) {\n\t\t\t\tconst dx = point[0] - x;\n\t\t\t\tconst dy = point[1] - y;\n\t\t\t\tif (dx * dx + dy * dy > outerRadiusSq + broadPhaseEpsilon) {\n\t\t\t\t\tpossible = false;\n\t\t\t\t\tbreak;\n\t\t\t\t}\n\t\t\t}\n\t\t\tif (!possible) continue;\n\n\t\t\tconst rayX = badgeX - x;\n\t\t\tconst rayY = badgeY - y;\n\t\t\tconst rayLength = Math.hypot(rayX, rayY);\n\t\t\tconst rayC = rayLength === 0 ? 1 : rayX / rayLength;\n\t\t\tconst rayS = rayLength === 0 ? 0 : rayY / rayLength;\n\t\t\tfor (const point of pixels) {\n\t\t\t\tconst dx = point[0] - x;\n\t\t\t\tconst dy = point[1] - y;\n\t\t\t\tconst u = dx * rayC + dy * rayS;\n\t\t\t\tconst v = -dx * rayS + dy * rayC;\n\t\t\t\tif (\n\t\t\t\t\tMath.abs(u) > rayFrameHalfWidth + broadPhaseEpsilon ||\n\t\t\t\t\tMath.abs(v) > rayFrameHalfHeight + broadPhaseEpsilon\n\t\t\t\t) {\n\t\t\t\t\tpossible = false;\n\t\t\t\t\tbreak;\n\t\t\t\t}\n\t\t\t}\n\t\t\tif (!possible) continue;\n\n\t\t\tfor (const axisOffset of axisOffsets) consider(x, y, rayC, rayS, axisOffset);\n\t\t}\n\t}\n'''
if text.count(old_loop) != 1:
    raise SystemExit(f'center loop count={text.count(old_loop)}')
path.write_text(text.replace(old_loop, new_loop, 1))
