from pathlib import Path

path = Path('packages/alg/src/detectors/threeFactor/ribbon.ts')
text = path.read_text()

old_sample = '''function sampleRgb(image: Float32Array, width: number, height: number, x: number, y: number, channel: number): number {\n\tconst x0 = Math.floor(x);\n\tconst y0 = Math.floor(y);\n\tconst ax = x - x0;\n\tconst ay = y - y0;\n\tconst p00 = (reflect(y0, height) * width + reflect(x0, width)) * 3 + channel;\n\tconst p10 = (reflect(y0, height) * width + reflect(x0 + 1, width)) * 3 + channel;\n\tconst p01 = (reflect(y0 + 1, height) * width + reflect(x0, width)) * 3 + channel;\n\tconst p11 = (reflect(y0 + 1, height) * width + reflect(x0 + 1, width)) * 3 + channel;\n\treturn image[p00] * (1 - ax) * (1 - ay) + image[p10] * ax * (1 - ay) + image[p01] * (1 - ax) * ay + image[p11] * ax * ay;\n}\n'''
new_sample = '''interface AxisSampleMap {\n\treadonly lo: Int32Array;\n\treadonly hi: Int32Array;\n\treadonly fraction: Float64Array;\n}\n\n/** One orientation/width pair translates every integer support-field cell by\n * four fixed offsets. Floor/reflection/fraction are axis-separable and depend\n * only on that offset, so compute them once per row/column instead of twelve\n * times per cell. The bilinear arithmetic itself remains byte-for-byte the\n * same channel expression as the original sampleRgb. */\nfunction axisSampleMap(size: number, offset: number): AxisSampleMap {\n\tconst lo = new Int32Array(size);\n\tconst hi = new Int32Array(size);\n\tconst fraction = new Float64Array(size);\n\tfor (let index = 0; index < size; index++) {\n\t\tconst coordinate = index + offset;\n\t\tconst base = Math.floor(coordinate);\n\t\tlo[index] = reflect(base, size);\n\t\thi[index] = reflect(base + 1, size);\n\t\tfraction[index] = coordinate - base;\n\t}\n\treturn { lo, hi, fraction };\n}\n\nfunction sampleRgbMappedInto(\n\timage: Float32Array,\n\twidth: number,\n\txMap: AxisSampleMap,\n\tyMap: AxisSampleMap,\n\tx: number,\n\ty: number,\n\tout: Float64Array,\n\toffset: number\n): void {\n\tconst ax = xMap.fraction[x];\n\tconst ay = yMap.fraction[y];\n\tconst p00 = (yMap.lo[y] * width + xMap.lo[x]) * 3;\n\tconst p10 = (yMap.lo[y] * width + xMap.hi[x]) * 3;\n\tconst p01 = (yMap.hi[y] * width + xMap.lo[x]) * 3;\n\tconst p11 = (yMap.hi[y] * width + xMap.hi[x]) * 3;\n\tfor (let channel = 0; channel < 3; channel++) {\n\t\tout[offset + channel] = image[p00 + channel] * (1 - ax) * (1 - ay) + image[p10 + channel] * ax * (1 - ay) + image[p01 + channel] * (1 - ax) * ay + image[p11 + channel] * ax * ay;\n\t}\n}\n'''
if text.count(old_sample) != 1:
    raise SystemExit(f'sample block count={text.count(old_sample)}')
text = text.replace(old_sample, new_sample, 1)

old_loop = '''\tconst delta = Math.max(1, knobs.gradientDeltaMultiplier / scale);\n\tfor (let orientation = 0; orientation < parameters.orientations; orientation++) {\n\t\tconst theta = (Math.PI * orientation) / parameters.orientations;\n\t\tconst nx = -Math.sin(theta);\n\t\tconst ny = Math.cos(theta);\n\t\tfor (const widthSrc of parameters.widthsSrc) {\n\t\t\tconst radius = widthSrc / (2 * scale);\n\t\t\tfor (let y = 0; y < height; y++) {\n\t\t\t\tfor (let x = 0; x < width; x++) {\n\t\t\t\t\tconst sample = (distance: number): [number, number, number] => {\n\t\t\t\t\t\tconst sx = x + nx * distance;\n\t\t\t\t\t\tconst sy = y + ny * distance;\n\t\t\t\t\t\treturn [\n\t\t\t\t\t\t\tsampleRgb(blurred, width, height, sx, sy, 0),\n\t\t\t\t\t\t\tsampleRgb(blurred, width, height, sx, sy, 1),\n\t\t\t\t\t\t\tsampleRgb(blurred, width, height, sx, sy, 2)\n\t\t\t\t\t\t];\n\t\t\t\t\t};\n\t\t\t\t\tconst a = sample(-(radius - delta));\n\t\t\t\t\tconst b = sample(-(radius + delta));\n\t\t\t\t\tconst c = sample(radius - delta);\n\t\t\t\t\tconst d = sample(radius + delta);\n\t\t\t\t\tconst d1r = a[0] - b[0];\n\t\t\t\t\tconst d1g = a[1] - b[1];\n\t\t\t\t\tconst d1b = a[2] - b[2];\n\t\t\t\t\tconst d2r = c[0] - d[0];\n\t\t\t\t\tconst d2g = c[1] - d[1];\n\t\t\t\t\tconst d2b = c[2] - d[2];\n\t\t\t\t\tconst dot = d1r * d2r + d1g * d2g + d1b * d2b;\n\t\t\t\t\tif (dot <= 0) continue;\n\t\t\t\t\tconst n1 = Math.hypot(d1r, d1g, d1b);\n\t\t\t\t\tconst n2 = Math.hypot(d2r, d2g, d2b);\n\t\t\t\t\tconst score = Math.min(n1, n2) * Math.min(1, dot / (n1 * n2 + 1e-6));\n\t\t\t\t\tconst cell = y * width + x;\n\t\t\t\t\tif (score > raw[cell]) {\n\t\t\t\t\t\traw[cell] = score;\n\t\t\t\t\t\tbestTheta[cell] = theta;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n'''
new_loop = '''\tconst delta = Math.max(1, knobs.gradientDeltaMultiplier / scale);\n\tconst samples = new Float64Array(12);\n\tfor (let orientation = 0; orientation < parameters.orientations; orientation++) {\n\t\tconst theta = (Math.PI * orientation) / parameters.orientations;\n\t\tconst nx = -Math.sin(theta);\n\t\tconst ny = Math.cos(theta);\n\t\tfor (const widthSrc of parameters.widthsSrc) {\n\t\t\tconst radius = widthSrc / (2 * scale);\n\t\t\tconst distanceA = -(radius - delta);\n\t\t\tconst distanceB = -(radius + delta);\n\t\t\tconst distanceC = radius - delta;\n\t\t\tconst distanceD = radius + delta;\n\t\t\tconst xA = axisSampleMap(width, nx * distanceA);\n\t\t\tconst yA = axisSampleMap(height, ny * distanceA);\n\t\t\tconst xB = axisSampleMap(width, nx * distanceB);\n\t\t\tconst yB = axisSampleMap(height, ny * distanceB);\n\t\t\tconst xC = axisSampleMap(width, nx * distanceC);\n\t\t\tconst yC = axisSampleMap(height, ny * distanceC);\n\t\t\tconst xD = axisSampleMap(width, nx * distanceD);\n\t\t\tconst yD = axisSampleMap(height, ny * distanceD);\n\t\t\tfor (let y = 0; y < height; y++) {\n\t\t\t\tfor (let x = 0; x < width; x++) {\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xA, yA, x, y, samples, 0);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xB, yB, x, y, samples, 3);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xC, yC, x, y, samples, 6);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xD, yD, x, y, samples, 9);\n\t\t\t\t\tconst d1r = samples[0] - samples[3];\n\t\t\t\t\tconst d1g = samples[1] - samples[4];\n\t\t\t\t\tconst d1b = samples[2] - samples[5];\n\t\t\t\t\tconst d2r = samples[6] - samples[9];\n\t\t\t\t\tconst d2g = samples[7] - samples[10];\n\t\t\t\t\tconst d2b = samples[8] - samples[11];\n\t\t\t\t\tconst dot = d1r * d2r + d1g * d2g + d1b * d2b;\n\t\t\t\t\tif (dot <= 0) continue;\n\t\t\t\t\tconst n1 = Math.hypot(d1r, d1g, d1b);\n\t\t\t\t\tconst n2 = Math.hypot(d2r, d2g, d2b);\n\t\t\t\t\tconst score = Math.min(n1, n2) * Math.min(1, dot / (n1 * n2 + 1e-6));\n\t\t\t\t\tconst cell = y * width + x;\n\t\t\t\t\tif (score > raw[cell]) {\n\t\t\t\t\t\traw[cell] = score;\n\t\t\t\t\t\tbestTheta[cell] = theta;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n'''
if text.count(old_loop) != 1:
    raise SystemExit(f'support loop count={text.count(old_loop)}')
path.write_text(text.replace(old_loop, new_loop, 1))
