from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one exact block, got {count}")
    p.write_text(text.replace(old, new, 1))


g3 = 'packages/alg/src/detectors/threeFactor/features/g3.teeRecovery.ts'
ribbon = 'packages/alg/src/detectors/threeFactor/ribbon.ts'

# V7: exact necessary-condition broad phase over the same center/angle lattice.
old_loop = '''\tfor (let y = minCenterY; y <= maxCenterY + 1e-9; y += 0.5) {\n\t\tfor (let x = minCenterX; x <= maxCenterX + 1e-9; x += 0.5) {\n\t\t\tconst rayX = badgeX - x;\n\t\t\tconst rayY = badgeY - y;\n\t\t\tconst rayLength = Math.hypot(rayX, rayY);\n\t\t\tconst rayC = rayLength === 0 ? 1 : rayX / rayLength;\n\t\t\tconst rayS = rayLength === 0 ? 0 : rayY / rayLength;\n\t\t\tfor (const axisOffset of axisOffsets) consider(x, y, rayC, rayS, axisOffset);\n\t\t}\n\t}\n'''
new_loop = '''\t// Exact broad phase over the SAME center lattice. Every pixel of any legal\n\t// rotated tee must satisfy both necessary bounds below. They only prove a\n\t// center impossible; they never remove a component, badge, or legal pose.\n\tconst outerRadiusSq = outerRadius * outerRadius;\n\tlet rayFrameHalfWidth = 0;\n\tlet rayFrameHalfHeight = 0;\n\tfor (const axisOffset of axisOffsets) {\n\t\trayFrameHalfWidth = Math.max(\n\t\t\trayFrameHalfWidth,\n\t\t\touterHalfWidth * Math.abs(axisOffset.c) + outerHalfHeight * Math.abs(axisOffset.s)\n\t\t);\n\t\trayFrameHalfHeight = Math.max(\n\t\t\trayFrameHalfHeight,\n\t\t\touterHalfWidth * Math.abs(axisOffset.s) + outerHalfHeight * Math.abs(axisOffset.c)\n\t\t);\n\t}\n\tconst broadPhaseEpsilon = 1e-9;\n\tfor (let y = minCenterY; y <= maxCenterY + 1e-9; y += 0.5) {\n\t\tfor (let x = minCenterX; x <= maxCenterX + 1e-9; x += 0.5) {\n\t\t\tlet possible = true;\n\t\t\tfor (const point of pixels) {\n\t\t\t\tconst dx = point[0] - x;\n\t\t\t\tconst dy = point[1] - y;\n\t\t\t\tif (dx * dx + dy * dy > outerRadiusSq + broadPhaseEpsilon) {\n\t\t\t\t\tpossible = false;\n\t\t\t\t\tbreak;\n\t\t\t\t}\n\t\t\t}\n\t\t\tif (!possible) continue;\n\n\t\t\tconst rayX = badgeX - x;\n\t\t\tconst rayY = badgeY - y;\n\t\t\tconst rayLength = Math.hypot(rayX, rayY);\n\t\t\tconst rayC = rayLength === 0 ? 1 : rayX / rayLength;\n\t\t\tconst rayS = rayLength === 0 ? 0 : rayY / rayLength;\n\t\t\tfor (const point of pixels) {\n\t\t\t\tconst dx = point[0] - x;\n\t\t\t\tconst dy = point[1] - y;\n\t\t\t\tconst u = dx * rayC + dy * rayS;\n\t\t\t\tconst v = -dx * rayS + dy * rayC;\n\t\t\t\tif (\n\t\t\t\t\tMath.abs(u) > rayFrameHalfWidth + broadPhaseEpsilon ||\n\t\t\t\t\tMath.abs(v) > rayFrameHalfHeight + broadPhaseEpsilon\n\t\t\t\t) {\n\t\t\t\t\tpossible = false;\n\t\t\t\t\tbreak;\n\t\t\t\t}\n\t\t\t}\n\t\t\tif (!possible) continue;\n\n\t\t\tfor (const axisOffset of axisOffsets) consider(x, y, rayC, rayS, axisOffset);\n\t\t}\n\t}\n'''
replace_once(g3, old_loop, new_loop)

# V8: compute the two RGB finite differences directly rather than materializing
# four RGB triples and immediately subtracting them.
old_helper = '''function sampleRgbMappedInto(\n\timage: Float32Array,\n\twidth: number,\n\txMap: AxisSampleMap,\n\tyMap: AxisSampleMap,\n\tx: number,\n\ty: number,\n\tout: Float64Array,\n\toffset: number\n): void {\n\tconst ax = xMap.fraction[x];\n\tconst ay = yMap.fraction[y];\n\tconst p00 = (yMap.lo[y] * width + xMap.lo[x]) * 3;\n\tconst p10 = (yMap.lo[y] * width + xMap.hi[x]) * 3;\n\tconst p01 = (yMap.hi[y] * width + xMap.lo[x]) * 3;\n\tconst p11 = (yMap.hi[y] * width + xMap.hi[x]) * 3;\n\tfor (let channel = 0; channel < 3; channel++) {\n\t\tout[offset + channel] = image[p00 + channel] * (1 - ax) * (1 - ay) + image[p10 + channel] * ax * (1 - ay) + image[p01 + channel] * (1 - ax) * ay + image[p11 + channel] * ax * ay;\n\t}\n}\n'''
new_helper = '''function sampleRgbDifferenceMappedInto(\n\timage: Float32Array,\n\twidth: number,\n\txMapA: AxisSampleMap,\n\tyMapA: AxisSampleMap,\n\txMapB: AxisSampleMap,\n\tyMapB: AxisSampleMap,\n\tx: number,\n\ty: number,\n\tout: Float64Array,\n\toffset: number\n): void {\n\tconst axA = xMapA.fraction[x];\n\tconst ayA = yMapA.fraction[y];\n\tconst p00A = (yMapA.lo[y] * width + xMapA.lo[x]) * 3;\n\tconst p10A = (yMapA.lo[y] * width + xMapA.hi[x]) * 3;\n\tconst p01A = (yMapA.hi[y] * width + xMapA.lo[x]) * 3;\n\tconst p11A = (yMapA.hi[y] * width + xMapA.hi[x]) * 3;\n\tconst axB = xMapB.fraction[x];\n\tconst ayB = yMapB.fraction[y];\n\tconst p00B = (yMapB.lo[y] * width + xMapB.lo[x]) * 3;\n\tconst p10B = (yMapB.lo[y] * width + xMapB.hi[x]) * 3;\n\tconst p01B = (yMapB.hi[y] * width + xMapB.lo[x]) * 3;\n\tconst p11B = (yMapB.hi[y] * width + xMapB.hi[x]) * 3;\n\tfor (let channel = 0; channel < 3; channel++) {\n\t\tconst a = image[p00A + channel] * (1 - axA) * (1 - ayA) + image[p10A + channel] * axA * (1 - ayA) + image[p01A + channel] * (1 - axA) * ayA + image[p11A + channel] * axA * ayA;\n\t\tconst b = image[p00B + channel] * (1 - axB) * (1 - ayB) + image[p10B + channel] * axB * (1 - ayB) + image[p01B + channel] * (1 - axB) * ayB + image[p11B + channel] * axB * ayB;\n\t\tout[offset + channel] = a - b;\n\t}\n}\n'''
replace_once(ribbon, old_helper, new_helper)
replace_once(ribbon, '\tconst samples = new Float64Array(12);\n', '\tconst gradients = new Float64Array(6);\n')
old_calls = '''\t\t\t\t\tsampleRgbMappedInto(blurred, width, xA, yA, x, y, samples, 0);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xB, yB, x, y, samples, 3);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xC, yC, x, y, samples, 6);\n\t\t\t\t\tsampleRgbMappedInto(blurred, width, xD, yD, x, y, samples, 9);\n\t\t\t\t\tconst d1r = samples[0] - samples[3];\n\t\t\t\t\tconst d1g = samples[1] - samples[4];\n\t\t\t\t\tconst d1b = samples[2] - samples[5];\n\t\t\t\t\tconst d2r = samples[6] - samples[9];\n\t\t\t\t\tconst d2g = samples[7] - samples[10];\n\t\t\t\t\tconst d2b = samples[8] - samples[11];\n'''
new_calls = '''\t\t\t\t\tsampleRgbDifferenceMappedInto(blurred, width, xA, yA, xB, yB, x, y, gradients, 0);\n\t\t\t\t\tsampleRgbDifferenceMappedInto(blurred, width, xC, yC, xD, yD, x, y, gradients, 3);\n\t\t\t\t\tconst d1r = gradients[0];\n\t\t\t\t\tconst d1g = gradients[1];\n\t\t\t\t\tconst d1b = gradients[2];\n\t\t\t\t\tconst d2r = gradients[3];\n\t\t\t\t\tconst d2g = gradients[4];\n\t\t\t\t\tconst d2b = gradients[5];\n'''
replace_once(ribbon, old_calls, new_calls)
