import { extname, join, resolve, dirname } from 'node:path';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import jpeg from 'jpeg-js';
import { PNG } from 'pngjs';
import { detectCorridorBendsCapsule, DEFAULT_DETECT_CORRIDOR_BENDS_CAPSULE_PARAMS } from '../../src/lib/autoAnnotation/corridorBendDetectionCapsule';
import type { CorridorBendRaster } from '../../src/lib/autoAnnotation/corridorBendDetection';
import { IMG_5641_GROUND_TRUTH } from '../../src/lib/autoAnnotation/courseGroundTruth';
import type { SourcePoint } from '../../src/lib/domain/annotatedRound';
import { buildAlexClarkGroundTruth, buildDashGroundTruth, loadAlexClarkFixture } from '../corridorBendGroundTruth';
import type { HoleBendTruth } from '../corridorBendGroundTruth';

/**
 * THROWAWAY validation script -- not part of the app, not wired into the
 * shared benchmark harness (`scripts/benchmark-corridor-bend-detection.ts`,
 * deliberately untouched). Two jobs:
 *
 * 1. Compare `detectCorridorBendsCapsule`'s output, hole-by-hole, against a
 *    FRESH run of the actual Python probes (`hole_path_capsule_fit.py` for
 *    Dash, `hole_path_alexclark_check.py` for AlexClark) -- JSON already
 *    generated by running those scripts directly, read from disk here.
 * 2. Compute full benchmark-style stats (exact bend-count match, false-bend
 *    rate on straight holes, location error, gutter containment, speed)
 *    against this repo's own ground-truth derivation
 *    (`scripts/corridorBendGroundTruth.ts`, imported read-only, not
 *    modified), mirroring `scripts/benchmark-corridor-bend-detection.ts`'s
 *    own scoring methodology so the numbers are apples-to-apples with the
 *    other three detectors' reported benchmark shape.
 */

const scriptPath = fileURLToPath(import.meta.url);
const projectRoot = resolve(dirname(scriptPath), '../..');

const DASH_IMAGE_PATH = join(projectRoot, 'resources/ribbon-reference/IMG_5641.jpg');
const ALEX_IMAGE_PATH = join(projectRoot, 'resources/stitch-annotate/AlexClark/AlexClark-McKinney-TX.jpg');
const PY_CAPSULE_JSON = process.argv[2];
const PY_ALEXCLARK_JSON = process.argv[3];
const LOCATION_WRONG_PX = 42;
const TIMING_REPETITIONS = 5;

// ---------------------------------------------------------------------------
// Raster decoding + Node-side crop -- copied from
// scripts/benchmark-corridor-bend-detection.ts (read-only reproduction in
// THIS throwaway script; that script itself is untouched).
// ---------------------------------------------------------------------------

interface DecodedRaster {
	readonly rgba: Uint8Array;
	readonly widthPx: number;
	readonly heightPx: number;
}

function decodeRaster(bytes: Uint8Array, fileName: string): DecodedRaster {
	const extension = extname(fileName).toLowerCase();
	if (extension === '.png') {
		const decoded = PNG.sync.read(Buffer.from(bytes));
		return { rgba: new Uint8Array(decoded.data), widthPx: decoded.width, heightPx: decoded.height };
	}
	if (extension === '.jpg' || extension === '.jpeg') {
		const decoded = jpeg.decode(Buffer.from(bytes), { useTArray: true });
		return { rgba: new Uint8Array(decoded.data), widthPx: decoded.width, heightPx: decoded.height };
	}
	throw new Error(`Unsupported image format '${extension}'.`);
}

function loadImage(path: string): DecodedRaster {
	return decodeRaster(new Uint8Array(readFileSync(path)), path);
}

const CROP_MARGIN_FRACTION = 0.4;
const CROP_MIN_MARGIN_PX = 40;
const CROP_MAX_MARGIN_PX = 260;
const CROP_MAX_DIM = 480;

function cropBounds(imageWidthPx: number, imageHeightPx: number, tee: SourcePoint, basket: SourcePoint) {
	const distance = Math.hypot(basket.xPx - tee.xPx, basket.yPx - tee.yPx);
	const margin = Math.min(CROP_MAX_MARGIN_PX, Math.max(CROP_MIN_MARGIN_PX, distance * CROP_MARGIN_FRACTION));
	return {
		x0: Math.max(0, Math.floor(Math.min(tee.xPx, basket.xPx) - margin)),
		y0: Math.max(0, Math.floor(Math.min(tee.yPx, basket.yPx) - margin)),
		x1: Math.min(imageWidthPx, Math.ceil(Math.max(tee.xPx, basket.xPx) + margin)),
		y1: Math.min(imageHeightPx, Math.ceil(Math.max(tee.yPx, basket.yPx) + margin))
	};
}

function cropAndDownscale(full: DecodedRaster, bounds: { x0: number; y0: number; x1: number; y1: number }, maxDim: number): CorridorBendRaster {
	const cropWidth = bounds.x1 - bounds.x0;
	const cropHeight = bounds.y1 - bounds.y0;
	const scale = Math.max(1, Math.max(cropWidth, cropHeight) / maxDim);
	const outWidth = Math.max(1, Math.round(cropWidth / scale));
	const outHeight = Math.max(1, Math.round(cropHeight / scale));
	const channels: 4 = 4;
	const data = new Uint8Array(outWidth * outHeight * channels);

	for (let oy = 0; oy < outHeight; oy += 1) {
		const sy0 = Math.floor(oy * scale);
		const sy1 = Math.max(sy0 + 1, Math.min(cropHeight, Math.floor((oy + 1) * scale)));
		for (let ox = 0; ox < outWidth; ox += 1) {
			const sx0 = Math.floor(ox * scale);
			const sx1 = Math.max(sx0 + 1, Math.min(cropWidth, Math.floor((ox + 1) * scale)));
			let r = 0;
			let g = 0;
			let b = 0;
			let a = 0;
			let count = 0;
			for (let sy = sy0; sy < sy1; sy += 1) {
				const rowBase = (bounds.y0 + sy) * full.widthPx;
				for (let sx = sx0; sx < sx1; sx += 1) {
					const p = (rowBase + bounds.x0 + sx) * 4;
					r += full.rgba[p];
					g += full.rgba[p + 1];
					b += full.rgba[p + 2];
					a += full.rgba[p + 3];
					count += 1;
				}
			}
			const op = (oy * outWidth + ox) * channels;
			data[op] = r / count;
			data[op + 1] = g / count;
			data[op + 2] = b / count;
			data[op + 3] = a / count;
		}
	}
	return { widthPx: outWidth, heightPx: outHeight, originXPx: bounds.x0, originYPx: bounds.y0, scale: cropWidth / outWidth, data, channels };
}

// ---------------------------------------------------------------------------
// Gutter containment -- point-in-polygon over the same hand-drawn gutter
// fixtures the Python probes use, sampled along the FULL predicted
// centerline (tee + bends + basket) at a 6px source-px step (matches the
// Python probes' sample(step=2) at their fixed 1/3 downscale: 2*3=6px).
// ---------------------------------------------------------------------------

function pointInPolygon(point: SourcePoint, polygon: readonly SourcePoint[]): boolean {
	let inside = false;
	for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) {
		const a = polygon[i];
		const b = polygon[j];
		const intersects = a.yPx > point.yPx !== b.yPx > point.yPx && point.xPx < ((b.xPx - a.xPx) * (point.yPx - a.yPx)) / (b.yPx - a.yPx) + a.xPx;
		if (intersects) inside = !inside;
	}
	return inside;
}

function dist(a: SourcePoint, b: SourcePoint): number {
	return Math.hypot(a.xPx - b.xPx, a.yPx - b.yPx);
}

function orientRight(tee: SourcePoint, left: readonly SourcePoint[], right: readonly SourcePoint[]): SourcePoint[] {
	if (dist(right[0], left[0]) + dist(right[right.length - 1], left[left.length - 1]) > dist(right[0], left[left.length - 1]) + dist(right[right.length - 1], left[0])) {
		return right.slice().reverse();
	}
	return right.slice();
}

function samplePolyline(points: readonly SourcePoint[], stepPx: number): SourcePoint[] {
	const out: SourcePoint[] = [];
	for (let i = 0; i < points.length - 1; i += 1) {
		const a = points[i];
		const b = points[i + 1];
		const segLen = Math.hypot(b.xPx - a.xPx, b.yPx - a.yPx);
		const n = Math.max(2, Math.floor(segLen / stepPx));
		for (let k = 0; k < n; k += 1) {
			const t = k / n;
			out.push({ xPx: a.xPx + (b.xPx - a.xPx) * t, yPx: a.yPx + (b.yPx - a.yPx) * t });
		}
	}
	out.push(points[points.length - 1]);
	return out;
}

function gutterContainment(centerline: readonly SourcePoint[], left: readonly SourcePoint[], rightRaw: readonly SourcePoint[]): number {
	const right = orientRight(centerline[0], left, rightRaw);
	const polygon = [...left, ...right.slice().reverse()];
	const samples = samplePolyline(centerline, 6);
	const inside = samples.filter((p) => pointInPolygon(p, polygon)).length;
	return inside / samples.length;
}

// ---------------------------------------------------------------------------
// Scoring -- mirrors scripts/benchmark-corridor-bend-detection.ts's
// scoreHole/aggregate (read-only reproduction, not imported since that
// script exports nothing and is explicitly not to be modified).
// ---------------------------------------------------------------------------

interface HoleScore {
	readonly holeNumber: number;
	readonly truthCount: number;
	readonly predictedCount: number;
	readonly status: 'GOOD' | 'COUNT WRONG' | 'LOCATION WRONG';
	readonly errorsPx: readonly number[];
	readonly isStraightTruth: boolean;
	readonly falseBend: boolean;
}

function nearestTruthDistancePx(point: SourcePoint, truthBends: readonly SourcePoint[]): number {
	return Math.min(...truthBends.map((truth) => Math.hypot(truth.xPx - point.xPx, truth.yPx - point.yPx)));
}

function scoreHole(truth: HoleBendTruth, predicted: readonly SourcePoint[]): HoleScore {
	const predictedCount = predicted.length;
	const isStraightTruth = truth.truthCount === 0;
	const falseBend = isStraightTruth && predictedCount > 0;
	if (predictedCount !== truth.truthCount) {
		return { holeNumber: truth.holeNumber, truthCount: truth.truthCount, predictedCount, status: 'COUNT WRONG', errorsPx: [], isStraightTruth, falseBend };
	}
	if (truth.truthCount === 0) {
		return { holeNumber: truth.holeNumber, truthCount: truth.truthCount, predictedCount, status: 'GOOD', errorsPx: [], isStraightTruth, falseBend };
	}
	const errorsPx = predicted.map((point) => nearestTruthDistancePx(point, truth.truthBends));
	const status = Math.max(...errorsPx) > LOCATION_WRONG_PX ? 'LOCATION WRONG' : 'GOOD';
	return { holeNumber: truth.holeNumber, truthCount: truth.truthCount, predictedCount, status, errorsPx, isStraightTruth, falseBend };
}

function median(values: readonly number[]): number | null {
	if (values.length === 0) return null;
	const sorted = values.slice().sort((a, b) => a - b);
	const mid = Math.floor(sorted.length / 2);
	return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid];
}
function mean(values: readonly number[]): number | null {
	return values.length === 0 ? null : values.reduce((s, v) => s + v, 0) / values.length;
}

function aggregate(scores: readonly HoleScore[]) {
	const exactCountMatches = scores.filter((s) => s.predictedCount === s.truthCount).length;
	const straight = scores.filter((s) => s.isStraightTruth);
	const falseBends = straight.filter((s) => s.falseBend).length;
	const errors = scores.flatMap((s) => s.errorsPx);
	return {
		holesEvaluated: scores.length,
		exactCountMatches,
		exactCountAccuracy: scores.length === 0 ? NaN : exactCountMatches / scores.length,
		straightHoleCount: straight.length,
		falseBendsOnStraightHoles: falseBends,
		falseBendRate: straight.length === 0 ? null : falseBends / straight.length,
		goodCount: scores.filter((s) => s.status === 'GOOD').length,
		locationWrongCount: scores.filter((s) => s.status === 'LOCATION WRONG').length,
		medianLocationErrorPx: median(errors),
		maxLocationErrorPx: errors.length === 0 ? null : Math.max(...errors)
	};
}

function timedMedian<T>(fn: () => T, repetitions: number): { result: T; medianMs: number } {
	let result: T | undefined;
	const times: number[] = [];
	for (let i = 0; i < repetitions; i += 1) {
		const start = performance.now();
		result = fn();
		times.push(performance.now() - start);
	}
	return { result: result as T, medianMs: median(times) ?? 0 };
}

function fmtPct(v: number | null): string {
	return v === null || Number.isNaN(v) ? 'n/a' : `${(v * 100).toFixed(0)}%`;
}
function fmtPx(v: number | null): string {
	return v === null ? 'n/a' : `${v.toFixed(1)}px`;
}
function fmtMs(v: number | null): string {
	return v === null ? 'n/a' : `${v.toFixed(2)}ms`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

interface PyHoleV2 {
	bends: number;
	capsuleScore: number;
	centerlinePx: [number, number][];
	gutterContainment?: number;
}
interface PyAlexHole {
	bends: number;
	scoresByK: Record<string, number>;
	containmentStageA: number;
	containmentRefined: number;
	centerlinePx: [number, number][];
}

function main(): void {
	console.log('=== Dash (IMG_5641), 18 holes ===');
	const dashImage = loadImage(DASH_IMAGE_PATH);
	const dashTruth = buildDashGroundTruth();
	const badgeByHole = new Map(IMG_5641_GROUND_TRUTH.badges.map((b) => [b.number, { xPx: b.xPx, yPx: b.yPx }]));
	const bentLabels = JSON.parse(readFileSync(join(projectRoot, 'resources/ribbon-reference/IMG_5641-bent-holes-labels.json'), 'utf8')) as {
		holes: { number: number; left: SourcePoint[]; right: SourcePoint[] }[];
	};
	const gutterByHole = new Map(bentLabels.holes.map((h) => [h.number, h]));
	const pyCapsule: Record<string, PyHoleV2> | null = PY_CAPSULE_JSON ? JSON.parse(readFileSync(PY_CAPSULE_JSON, 'utf8')) : null;

	const dashScores: HoleScore[] = [];
	const dashTimesMs: number[] = [];
	let pyBendCountAgree = 0;
	let pyExactPositionAgree = 0;
	const disagreements: string[] = [];

	for (const hole of IMG_5641_GROUND_TRUTH.holes) {
		const badge = badgeByHole.get(hole.number);
		const bounds = cropBounds(dashImage.widthPx, dashImage.heightPx, hole.tee, hole.basket);
		const { result: predicted, medianMs } = timedMedian(() => {
			const raster = cropAndDownscale(dashImage, bounds, CROP_MAX_DIM);
			return detectCorridorBendsCapsule(raster, hole.tee, hole.basket, badge, DEFAULT_DETECT_CORRIDOR_BENDS_CAPSULE_PARAMS);
		}, TIMING_REPETITIONS);
		dashTimesMs.push(medianMs);
		const truth = dashTruth.find((t) => t.holeNumber === hole.number)!;
		const score = scoreHole(truth, predicted);
		dashScores.push(score);

		const gutter = gutterByHole.get(hole.number);
		const containment = gutter ? gutterContainment([hole.tee, ...predicted, hole.basket], gutter.left, gutter.right) : null;

		if (pyCapsule) {
			const py = pyCapsule[String(hole.number)];
			const pyBends = py.bends;
			const bendCountMatch = pyBends === predicted.length;
			if (bendCountMatch) pyBendCountAgree += 1;
			let positionAgree = false;
			if (bendCountMatch) {
				const pyPts = py.centerlinePx.slice(1, py.centerlinePx.length - 1).slice(-pyBends || undefined);
				// py.centerlinePx always includes the badge as point[1] when anchored;
				// the last `pyBends` interior points (excluding badge) are the actual bends.
				const pyBendPts = py.centerlinePx.slice(2, py.centerlinePx.length - 1);
				const maxDelta = pyBends === 0 ? 0 : Math.max(...predicted.map((p, i) => Math.hypot(p.xPx - pyBendPts[i][0], p.yPx - pyBendPts[i][1])));
				positionAgree = maxDelta <= LOCATION_WRONG_PX;
				if (positionAgree) pyExactPositionAgree += 1;
			}
			const statusStr = `${bendCountMatch ? 'count-match' : 'COUNT-DIFF'} py=${pyBends} ts=${predicted.length}`;
			if (!bendCountMatch || !positionAgree) {
				disagreements.push(`hole ${hole.number}: ${statusStr}${bendCountMatch ? ` (position ${positionAgree ? 'OK' : 'DIFFERS'})` : ''}`);
			}
			console.log(
				`hole ${String(hole.number).padStart(2)}: TS bends=${predicted.length} status=${score.status.padEnd(13)} truth=${truth.truthCount} py.bends=${pyBends} ${bendCountMatch ? 'MATCH' : 'DIFFER'} containment=${containment !== null ? (containment * 100).toFixed(1) + '%' : 'n/a'} speed=${medianMs.toFixed(2)}ms`
			);
		}
	}

	console.log(`\nDash vs FRESH Python (hole_path_capsule_fit.py): bend-count agreement ${pyBendCountAgree}/18, position agreement (within ${LOCATION_WRONG_PX}px, given count matches) ${pyExactPositionAgree}/18`);
	if (disagreements.length > 0) {
		console.log('Disagreements:');
		disagreements.forEach((d) => console.log(`  ${d}`));
	} else {
		console.log('No disagreements.');
	}

	const dashAgg = aggregate(dashScores);
	console.log('\nDash aggregate (vs this repo\'s own ground-truth derivation):');
	console.log(
		`  exact count accuracy ${fmtPct(dashAgg.exactCountAccuracy)} (${dashAgg.exactCountMatches}/${dashAgg.holesEvaluated}), false-bend rate on straight holes ${dashAgg.falseBendsOnStraightHoles}/${dashAgg.straightHoleCount} (${fmtPct(dashAgg.falseBendRate)}), good ${dashAgg.goodCount}, location-wrong ${dashAgg.locationWrongCount}, median loc err ${fmtPx(dashAgg.medianLocationErrorPx)}, max ${fmtPx(dashAgg.maxLocationErrorPx)}`
	);
	console.log(`  speed: median ${fmtMs(median(dashTimesMs))}/hole, mean ${fmtMs(mean(dashTimesMs))}/hole`);

	// -------------------------------------------------------------------
	console.log('\n=== AlexClark-McKinney-TX, 3 labeled bent holes (unanchored) ===');
	const alexImage = loadImage(ALEX_IMAGE_PATH);
	const alexTruth = buildAlexClarkGroundTruth();
	const alexFixture = loadAlexClarkFixture();
	const pyAlex: Record<string, PyAlexHole> | null = PY_ALEXCLARK_JSON ? JSON.parse(readFileSync(PY_ALEXCLARK_JSON, 'utf8')) : null;

	const alexScores: HoleScore[] = [];
	const alexTimesMs: number[] = [];
	let alexPyBendCountAgree = 0;

	for (const hole of alexFixture.holes) {
		const number = Number(hole.number);
		const bounds = cropBounds(alexImage.widthPx, alexImage.heightPx, hole.tee, hole.basket);
		const { result: predicted, medianMs } = timedMedian(() => {
			const raster = cropAndDownscale(alexImage, bounds, CROP_MAX_DIM);
			return detectCorridorBendsCapsule(raster, hole.tee, hole.basket, undefined, DEFAULT_DETECT_CORRIDOR_BENDS_CAPSULE_PARAMS);
		}, TIMING_REPETITIONS);
		alexTimesMs.push(medianMs);
		const truth = alexTruth.find((t) => t.holeNumber === number)!;
		const score = scoreHole(truth, predicted);
		alexScores.push(score);
		const containment = gutterContainment([hole.tee, ...predicted, hole.basket], hole.left, hole.right);

		let pyBends: number | null = null;
		let bendCountMatch = false;
		if (pyAlex) {
			const py = pyAlex[String(number)];
			pyBends = py.bends;
			bendCountMatch = pyBends === predicted.length;
			if (bendCountMatch) alexPyBendCountAgree += 1;
		}
		console.log(
			`label-hole ${number}: TS bends=${predicted.length} status=${score.status.padEnd(13)} truth=${truth.truthCount} py.bends=${pyBends} ${pyAlex ? (bendCountMatch ? 'MATCH' : 'DIFFER') : ''} containment=${(containment * 100).toFixed(1)}% speed=${medianMs.toFixed(2)}ms`
		);
	}
	console.log(`\nAlexClark vs FRESH Python (hole_path_alexclark_check.py): bend-count agreement ${alexPyBendCountAgree}/3`);

	const alexAgg = aggregate(alexScores);
	console.log('\nAlexClark aggregate:');
	console.log(
		`  exact count accuracy ${fmtPct(alexAgg.exactCountAccuracy)} (${alexAgg.exactCountMatches}/${alexAgg.holesEvaluated}), good ${alexAgg.goodCount}, location-wrong ${alexAgg.locationWrongCount}, median loc err ${fmtPx(alexAgg.medianLocationErrorPx)}, max ${fmtPx(alexAgg.maxLocationErrorPx)}`
	);
	console.log(`  speed: median ${fmtMs(median(alexTimesMs))}/hole, mean ${fmtMs(mean(alexTimesMs))}/hole`);

	const outDir = '/tmp/claude-0/-home-user-ChainSpot/e69a8ea3-488c-5118-a901-e7298706f764/scratchpad';
	mkdirSync(outDir, { recursive: true });
	writeFileSync(
		join(outDir, 'capsule-ts-validation-report.json'),
		JSON.stringify({ dash: { scores: dashScores, aggregate: dashAgg }, alexClark: { scores: alexScores, aggregate: alexAgg } }, null, 2)
	);
}

main();
