// Observability for the tiny logistic-regression digit classifier
// (src/lib/nuthing/digits/logistic.ts): renders each class's learned W row
// -- one weight per pixel of the 24x32 mask -- back into its spatial
// position, so a human can see WHICH cells push evidence toward a digit
// and which push away from it (e.g. "these cells made it think 3 instead
// of 8").
//
// Reads:
//   resources/nuthing-p2/digits/models/logistic.json (variant 1: real-only,
//     the classifier this repo's observability commentary is written
//     against; run again by hand against logistic-synth.json if a synthetic
//     coefficient map is ever needed)
//
// Writes:
//   docs/nuthing-p2/logistic-coefficients.md      (ASCII maps, all 10 classes)
//   /workspace/nuthing-work/digits/logistic-coefficients.png (PNG grid)
//   resources/nuthing-p2/digits/logistic-coefficients.png    (same PNG, committed)
//
// Usage: npx tsx scripts/nuthing/visualize-logistic.ts

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import { DIGIT_W, DIGIT_H } from '../../src/lib/nuthing/digits/normalize';
import type { LogisticModel } from '../../src/lib/nuthing/digits/logistic';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

const MODEL_PATH = join(REPO_ROOT, 'resources', 'nuthing-p2', 'digits', 'models', 'logistic.json');
const DOC_PATH = join(REPO_ROOT, 'docs', 'nuthing-p2', 'logistic-coefficients.md');
const PNG_PATHS = [
  '/workspace/nuthing-work/digits/logistic-coefficients.png',
  join(REPO_ROOT, 'resources', 'nuthing-p2', 'digits', 'logistic-coefficients.png'),
];

// ---- ASCII rendering -------------------------------------------------

// Signed-intensity buckets, strongest to weakest: '#'/'+' push TOWARD this
// class, '-'/'=' push AWAY from it, '·' (middle dot) is ~zero.
const BUCKET_STRONG_POS = '#';
const BUCKET_WEAK_POS = '+';
const BUCKET_ZERO = '·';
const BUCKET_WEAK_NEG = '-';
const BUCKET_STRONG_NEG = '=';
const STRONG_FRACTION = 0.66; // of this class's max |w|
const WEAK_FRACTION = 0.15;

function asciiMapForRow(row: number[]): { grid: string[]; maxAbs: number } {
  let maxAbs = 0;
  for (const w of row) maxAbs = Math.max(maxAbs, Math.abs(w));
  const strongT = maxAbs * STRONG_FRACTION;
  const weakT = maxAbs * WEAK_FRACTION;
  const lines: string[] = [];
  for (let y = 0; y < DIGIT_H; y++) {
    let line = '';
    for (let x = 0; x < DIGIT_W; x++) {
      const w = row[y * DIGIT_W + x];
      if (w >= strongT) line += BUCKET_STRONG_POS;
      else if (w >= weakT) line += BUCKET_WEAK_POS;
      else if (w <= -strongT) line += BUCKET_STRONG_NEG;
      else if (w <= -weakT) line += BUCKET_WEAK_NEG;
      else line += BUCKET_ZERO;
    }
    lines.push(line);
  }
  return { grid: lines, maxAbs };
}

function writeAsciiDoc(model: LogisticModel): void {
  const lines: string[] = [];
  lines.push('# Logistic classifier coefficient maps (ASCII)');
  lines.push('');
  lines.push(
    'Generated by `scripts/nuthing/visualize-logistic.ts` from ' +
      '`resources/nuthing-p2/digits/models/logistic.json` (variant 1, real-only train). ' +
      'Each block is one class\'s learned weight row `W[k]` reshaped back to its ' +
      `${DIGIT_W}x${DIGIT_H} spatial layout (row-major, same orientation as the normalized mask). ` +
      'Bucketing is per-class, relative to that class\'s own max |weight| ' +
      `(strong >= ${STRONG_FRACTION}x max, weak >= ${WEAK_FRACTION}x max):`,
  );
  lines.push('');
  lines.push(`- \`${BUCKET_STRONG_POS}\` strong positive (ink here strongly favors this digit)`);
  lines.push(`- \`${BUCKET_WEAK_POS}\` weak positive`);
  lines.push(`- \`${BUCKET_ZERO}\` ~zero (this pixel carries little evidence either way)`);
  lines.push(`- \`${BUCKET_WEAK_NEG}\` weak negative`);
  lines.push(`- \`${BUCKET_STRONG_NEG}\` strong negative (ink here strongly argues against this digit)`);
  lines.push('');
  lines.push(`See also: PNG grid at \`resources/nuthing-p2/digits/logistic-coefficients.png\` ` +
    '(red=negative, green=positive, intensity=|w| normalized per class), and the spatial-region ' +
    'commentary in `docs/nuthing-p2/logistic-classifier.md`.');
  lines.push('');
  for (let c = 0; c < model.classes.length; c++) {
    const { grid, maxAbs } = asciiMapForRow(model.W[c]);
    lines.push(`## Class '${model.classes[c]}' (bias b=${model.b[c].toFixed(4)}, max |w|=${maxAbs.toFixed(4)})`);
    lines.push('');
    lines.push('```');
    lines.push(...grid);
    lines.push('```');
    lines.push('');
  }
  writeFileSync(DOC_PATH, lines.join('\n'));
  console.log(`ASCII coefficient maps -> ${DOC_PATH}`);
}

// ---- PNG rendering -----------------------------------------------------

// Minimal 3x5 bitmap font for digits 0-9, used only to label each tile.
const FONT_3X5: Record<string, string[]> = {
  '0': ['111', '101', '101', '101', '111'],
  '1': ['010', '110', '010', '010', '111'],
  '2': ['111', '001', '111', '100', '111'],
  '3': ['111', '001', '111', '001', '111'],
  '4': ['101', '101', '111', '001', '001'],
  '5': ['111', '100', '111', '001', '111'],
  '6': ['111', '100', '111', '101', '111'],
  '7': ['111', '001', '001', '001', '001'],
  '8': ['111', '101', '111', '101', '111'],
  '9': ['111', '101', '111', '001', '111'],
};

const TILE_SCALE = 6; // upscale factor for each 24x32 mask cell -> 6x6 px
const FONT_SCALE = 3;
const LABEL_H = 24;
const PADDING = 12;
const COLS = 5;
const ROWS = 2;
const BG = { r: 0x20, g: 0x20, b: 0x20 };
const LABEL_FG = { r: 0xff, g: 0xff, b: 0xff };

function setPixel(png: PNG, x: number, y: number, r: number, g: number, b: number, a = 255): void {
  if (x < 0 || y < 0 || x >= png.width || y >= png.height) return;
  const idx = (png.width * y + x) << 2;
  png.data[idx] = r;
  png.data[idx + 1] = g;
  png.data[idx + 2] = b;
  png.data[idx + 3] = a;
}

function drawDigitLabel(png: PNG, digit: string, originX: number, originY: number): void {
  const glyph = FONT_3X5[digit];
  if (!glyph) return;
  for (let gy = 0; gy < glyph.length; gy++) {
    for (let gx = 0; gx < glyph[gy].length; gx++) {
      if (glyph[gy][gx] !== '1') continue;
      for (let sy = 0; sy < FONT_SCALE; sy++) {
        for (let sx = 0; sx < FONT_SCALE; sx++) {
          setPixel(
            png,
            originX + gx * FONT_SCALE + sx,
            originY + gy * FONT_SCALE + sy,
            LABEL_FG.r,
            LABEL_FG.g,
            LABEL_FG.b,
          );
        }
      }
    }
  }
}

function writePngGrid(model: LogisticModel): void {
  const tileW = DIGIT_W * TILE_SCALE;
  const tileH = DIGIT_H * TILE_SCALE;
  const blockW = tileW;
  const blockH = LABEL_H + tileH;
  const width = COLS * blockW + (COLS + 1) * PADDING;
  const height = ROWS * blockH + (ROWS + 1) * PADDING;

  const png = new PNG({ width, height });
  // Fill background.
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) setPixel(png, x, y, BG.r, BG.g, BG.b);
  }

  for (let c = 0; c < model.classes.length; c++) {
    const row = model.W[c];
    let maxAbs = 0;
    for (const w of row) maxAbs = Math.max(maxAbs, Math.abs(w));
    const col = c % COLS;
    const gridRow = Math.floor(c / COLS);
    const blockX = PADDING + col * (blockW + PADDING);
    const blockY = PADDING + gridRow * (blockH + PADDING);

    // Label: the digit this tile's weights are FOR.
    drawDigitLabel(png, model.classes[c], blockX, blockY);

    const tileY0 = blockY + LABEL_H;
    for (let y = 0; y < DIGIT_H; y++) {
      for (let x = 0; x < DIGIT_W; x++) {
        const w = row[y * DIGIT_W + x];
        const intensity = maxAbs > 0 ? Math.round((255 * Math.abs(w)) / maxAbs) : 0;
        const r = w < 0 ? intensity : 0;
        const g = w >= 0 ? intensity : 0;
        for (let sy = 0; sy < TILE_SCALE; sy++) {
          for (let sx = 0; sx < TILE_SCALE; sx++) {
            setPixel(png, blockX + x * TILE_SCALE + sx, tileY0 + y * TILE_SCALE + sy, r, g, 0);
          }
        }
      }
    }
  }

  const buf = PNG.sync.write(png);
  for (const p of PNG_PATHS) {
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, buf);
    console.log(`PNG coefficient grid -> ${p}`);
  }
}

function main(): void {
  mkdirSync(dirname(DOC_PATH), { recursive: true });
  const model = JSON.parse(readFileSync(MODEL_PATH, 'utf8')) as LogisticModel;
  writeAsciiDoc(model);
  writePngGrid(model);
}

main();
