/**
 * Regenerates src/lib/autoAnnotation/teeAppearanceTemplates.ts.
 *
 * Template source: AlexClarkSet's 13 legitimate P1 tee detections (raw
 * candidate array indices 0-11 and 20 -- hand-verified against real tee-pad
 * positions; see docs/benchmarks/p1-tee-appearance-verifier.md). Evaluation
 * target for cross-validating this bank is GoldenTeeSet, held fully out of
 * template construction -- see that doc for the held-out numbers this
 * threshold is based on.
 *
 * Usage: npx tsx scripts/generate-tee-appearance-templates.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { unzipSync } from 'fflate';
import jpeg from 'jpeg-js';
import { detectRawObjectMask } from '../src/lib/autoAnnotation/rawObjectMask';
import { extractCanonicalTeePatch, TEE_APPEARANCE_CANONICAL_SIZE } from '../src/lib/autoAnnotation/teeAppearance';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const ALEX_LEGIT_INDEXES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 20];

function decodeCourseRaster(zipPath: string) {
	const entries = unzipSync(readFileSync(zipPath));
	const bytes = entries['images/source-original.jpg'];
	if (!bytes) throw new Error(`${zipPath}: no images/source-original.jpg`);
	const decoded = jpeg.decode(bytes, { useTArray: true, maxMemoryUsageInMB: 2048 });
	return { rgba: decoded.data, widthPx: decoded.width, heightPx: decoded.height };
}

function main() {
	const raster = decodeCourseRaster(join(ROOT, 'resources/AlexClarkSet.chainspot.zip'));
	const mask = detectRawObjectMask(raster);
	if (mask.tees.length !== 21) {
		throw new Error(`AlexClarkSet tee count changed (${mask.tees.length}, expected 21) -- template indexes need re-verifying`);
	}

	const patches = ALEX_LEGIT_INDEXES.map((i) => {
		const patch = extractCanonicalTeePatch(raster, mask.tees[i]);
		return Array.from(patch, (v) => Math.round(v));
	});

	const banner = `/**
 * Generated by scripts/generate-tee-appearance-templates.ts -- do not hand-edit.
 *
 * ${patches.length} canonical (${TEE_APPEARANCE_CANONICAL_SIZE}x${TEE_APPEARANCE_CANONICAL_SIZE}) rotation-normalized
 * brightness patches, source: AlexClarkSet's legitimate P1 tee detections
 * (raw candidate indexes ${JSON.stringify(ALEX_LEGIT_INDEXES)}).
 * Values are 0-255 brightness (max of R/G/B), row-major.
 */

export const TEE_TEMPLATE_PATCH_SIZE = ${TEE_APPEARANCE_CANONICAL_SIZE};

export const TEE_TEMPLATE_BANK: readonly (readonly number[])[] = ${JSON.stringify(patches)};

export const TEE_TEMPLATE_BANK_180: readonly (readonly number[])[] = TEE_TEMPLATE_BANK.map(
	(patch) => [...patch].reverse()
);
`;

	writeFileSync(join(ROOT, 'src/lib/autoAnnotation/teeAppearanceTemplates.ts'), banner);
	console.log(`Wrote ${patches.length} templates to src/lib/autoAnnotation/teeAppearanceTemplates.ts`);
}

main();
