// cleanBasketFamily knob-tuning investigation — CHSPT-82, Phase 1
// (measure-first). Harvests every cleanBasketFamily decision's testimony
// from the family-on run's trace across all 4 in-scope courses, cross-tags
// each against ground truth (TRUE = matches a truth basket within 26px,
// PHANTOM otherwise), reports min/max/quartiles per metric (pooled AND per
// course), and renders a TRUE-vs-PHANTOM strip chart per metric to
// artifacts/sweep/family-tuning/ (gitignored, regenerated by this test).
//
// Purely observational — no expect() on distributions or thresholds. This
// file's job is to produce the numbers and images the tuning decision gets
// made FROM; the decision itself (new knob defaults) is a conscious source
// edit made separately, with its own re-pin and verification pass.

import { describe, test } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_EXECUTION, parseConfig, resolveConfig, runThreeFactor, canonicalJson, sha256Hex } from '@chainspot/alg/detectors/threeFactor';
import familyOnConfigJson from '@chainspot/alg/detectors/threeFactor/configs/family-on.json';
import basketSpriteData from '@chainspot/alg/detectors/threeFactor/assets/basket-sprite.json';
import { COURSES, DASHSTRACK_VIA_ANNOTATED, loadCourseRaster, loadCourseTruth, type CourseSpec } from './helpers/courseFixture';
import { harvestCleanBasketTestimony, quartiles, type HarvestedDecision, type Quartiles } from './helpers/familyTuningHarvest';
import { renderHistogramPng } from './helpers/histogramRender';

const ASSOCIATION_TOLERANCE_PX = 26;
const ALL_COURSES: readonly CourseSpec[] = [DASHSTRACK_VIA_ANNOTATED, ...COURSES];

const HERE = dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = resolve(HERE, '../../artifacts/sweep/family-tuning');

// Current (pre-tune) knob defaults, for the threshold lines drawn on each chart.
const CURRENT_KNOBS = {
	areaRatioMin: 0.96,
	areaRatioMax: 1.03,
	whiteCoverageMin: 0.96,
	darkShellMin: 0.5,
	darkCoherenceMin: 0.8
};

function fmtQ(label: string, q: Quartiles): string {
	return `${label} n=${q.n} min=${q.min.toFixed(3)} q1=${q.q1.toFixed(3)} median=${q.median.toFixed(3)} q3=${q.q3.toFixed(3)} max=${q.max.toFixed(3)}`;
}

describe('cleanBasketFamily knob-tuning Phase 1 (measure-first harvest)', () => {
	test(
		'harvest + report + render',
		async () => {
			const resolved = resolveConfig(parseConfig(familyOnConfigJson), DEFAULT_EXECUTION);
			const paramsHash = await sha256Hex(canonicalJson(resolved));
			const tipOffset = (resolved.features['sprite']?.knobs.tipOffset as number | undefined) ?? 4;
			const template = basketSpriteData as { width: number; height: number };

			const all: HarvestedDecision[] = [];
			for (const spec of ALL_COURSES) {
				const raster = loadCourseRaster(spec);
				const truth = loadCourseTruth(spec).holes;
				const run = runThreeFactor(raster, { config: resolved, paramsHash });
				const decisions = harvestCleanBasketTestimony(
					spec.name,
					run,
					truth,
					template.width,
					template.height,
					tipOffset,
					ASSOCIATION_TOLERANCE_PX
				);
				console.log(
					`[familyTuning] ${spec.name}: ${decisions.length} decisions (${decisions.filter((d) => d.stage === 'metrics').length} reached metric evaluation)`
				);
				all.push(...decisions);
			}

			const metricDecisions = all.filter((d) => d.stage === 'metrics');
			const nonMetric = all.filter((d) => d.stage !== 'metrics');
			console.log(
				`[familyTuning] TOTAL ${all.length} decisions: ${metricDecisions.length} reached metric evaluation, ${nonMetric.length} rejected earlier (no-component=${nonMetric.filter((d) => d.stage === 'no-component').length}, bad-bbox=${nonMetric.filter((d) => d.stage === 'bad-bbox').length})`
			);

			const metrics: (keyof Pick<HarvestedDecision, 'spriteScore' | 'areaRatio' | 'whiteCoverage' | 'darkShell' | 'darkCoherence'>)[] = [
				'spriteScore',
				'areaRatio',
				'whiteCoverage',
				'darkShell',
				'darkCoherence'
			];

			const domains: Record<string, [number, number]> = {
				spriteScore: [0, 1],
				areaRatio: [0.5, 1.5],
				whiteCoverage: [0, 1],
				darkShell: [0, 1],
				darkCoherence: [0, 1]
			};
			const thresholdKeys: Record<string, string[]> = {
				areaRatio: ['areaRatioMin', 'areaRatioMax'],
				whiteCoverage: ['whiteCoverageMin'],
				darkShell: ['darkShellMin'],
				darkCoherence: ['darkCoherenceMin']
			};

			mkdirSync(ARTIFACTS_DIR, { recursive: true });

			for (const metric of metrics) {
				const trueVals = metricDecisions.filter((d) => d.isTrue).map((d) => d[metric]);
				const phantomVals = metricDecisions.filter((d) => !d.isTrue).map((d) => d[metric]);
				console.log(`--- ${metric} (pooled) ---`);
				console.log(fmtQ('TRUE   ', quartiles(trueVals)));
				console.log(fmtQ('PHANTOM', quartiles(phantomVals)));
				for (const spec of ALL_COURSES) {
					const courseTrue = metricDecisions.filter((d) => d.course === spec.name && d.isTrue).map((d) => d[metric]);
					const coursePhantom = metricDecisions.filter((d) => d.course === spec.name && !d.isTrue).map((d) => d[metric]);
					console.log(`  [${spec.name}] ${fmtQ('TRUE   ', quartiles(courseTrue))}`);
					console.log(`  [${spec.name}] ${fmtQ('PHANTOM', quartiles(coursePhantom))}`);
				}

				const thresholds: Record<string, number> = {};
				for (const key of thresholdKeys[metric] ?? []) thresholds[key] = (CURRENT_KNOBS as Record<string, number>)[key];
				const png = renderHistogramPng({
					metricName: metric,
					trueValues: trueVals,
					phantomValues: phantomVals,
					domainMin: domains[metric][0],
					domainMax: domains[metric][1],
					thresholds
				});
				const path = resolve(ARTIFACTS_DIR, `${metric}.png`);
				writeFileSync(path, png);
				console.log(`[familyTuning] wrote ${path}`);
			}

			// Which TRUE baskets got wrongly rejected, and by which knob, by what margin.
			const wronglyRejected = metricDecisions.filter((d) => d.isTrue && !d.accepted);
			console.log(`[familyTuning] wrongly-rejected TRUE baskets: ${wronglyRejected.length}`);
			for (const d of wronglyRejected) {
				console.log(
					`  [${d.course}] hole=${d.matchedHoleNumber} distPx=${d.matchDistPx.toFixed(1)} reason="${d.reason}" ` +
						`areaRatio=${d.areaRatio.toFixed(3)} whiteCoverage=${d.whiteCoverage.toFixed(3)} darkShell=${d.darkShell.toFixed(3)} darkCoherence=${d.darkCoherence.toFixed(3)}`
				);
			}
		},
		180000
	);
});
